sudo: required
language: generic

services:
  - docker

before_script:
  - docker build -t ng2iotile .

script:
  - docker run --rm ng2iotile
  - docker run --rm -v $PWD:/usr/src/app ng2iotile run build

