sudo: required
language: node_js

services:
  - docker

before_install:
  - docker build -t ng2iotile .

script:
- docker run --rm ng2iotile
- docker run --rm -v $PWD:/usr/src/app ng2iotile run build

